http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/analytics/report'
serviceEndpoints:
  httpbin:
    url: 'http://localhost:3000/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      #- key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              headers: { 'api-key': GQBPHTF-HFJMXYH-N362PW6-1FTPYXP }
              changeOrigin: true
